version: 2
jobs:
  build:
    docker:
      - image: aperezdc/ci-wpebackend:latest
        user: build
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            rm -rf _p
            mkdir -p _p/src/_build
            curl -sLo _p/PKGBUILD 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=wpebackend-git'
            ln -sf "$(pwd)" _p/src/wpebackend-git
            cd _p
      - run:
          name: Build
          command: |
            cd _p
            makepkg --skipinteg --nosign --noextract --force --nocolor
      - run:
          name: Check
          command: |
            cd _p
            while read -r pkg ; do
              echo "=== ${pkg} ==="
              namcap "${pkg}"
              echo ''
            done < <(makepkg --packagelist) | tee namcap.log
