version: 2
jobs:
  build:
    docker:
      - image: aperezdc/ci-wpebackend:latest
        user: build
    steps:
      - checkout
      - run:
          name: Build
          command: |
            rm -rf _p packages
            mkdir -p _p/src/_build packages
            curl -sLo _p/PKGBUILD 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=libwpe-git'
            ln -sf "$(pwd)" _p/src/libwpe-git
            cd _p
            makepkg --skipinteg --nosign --noextract --force --nocolor
            while read -r pkg ; do
              printf '======= %s ======\n' "$(basename "${pkg}")"
              namcap "${pkg}"
              ln "${pkg}" ../packages/
            done < <(makepkg --packagelist) | tee ../packages/namcap.log
      - store_artifacts:
          path: packages/
          destination: output
